language: r
pandoc_version: 1.19.2.1
    
script:
  - Rscript -e 'remotes::install_github("RLesur/klippy")'
  - bash render-book.sh
  - rm DESCRIPTION
  - mv DESCRIPTION-pkgdown DESCRIPTION
  - Rscript -e 'pkgdown::build_site()'
  - cp -r _book/ docs/doc
  - cp -rf example-thesis/_book/*.pdf docs/doc/
  
cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/example-thesis/_bookdown_files
    - doc-v1

after_success:
  - mv doc-v1/ docs/
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs # Book output directory
  on:
    branch: master
